plugins {
    id "com.android.library"
}

android {
    namespace "android"
    compileSdk = 37

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdk 30
    }
    lint {
        targetSdk 37
    }
    testOptions {
        targetSdk 37
    }

}

java {
    sourceCompatibility JavaVersion.VERSION_1_7
    targetCompatibility JavaVersion.VERSION_1_7
}
